# Generated by Django 4.2 on 2024-10-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='News.region'),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category'),
        ),
    ]
