# Generated by Django 4.2 on 2024-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_new_region_alter_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(default='ss', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
